name: "Deploy Gitpod"
description: "Deploys Gitpod to an existing preview environment"
inputs:
  name:
    description: "The name of the preview environment to deploy Gitpod to"
    required: false
  version:
    description: "The version of Gitpod to install"
    required: true
  previewctl_hash:
    description: "The Leeway hash of the dev/preview/previewctl:docker package to be used when downloading previewclt"
    required: false
  with_dedicated_emu:
    description: "Dedicated Config"
    required: false
  analytics:
    description: "With analytics"
    required: false
  workspace_feature_flags:
    description: "Workspace feature flags"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
