name: "Delete preview environment"
description: "Deletes a preview environment"
inputs:
  name:
    description: "The name of the preview environment"
    required: true
  previewctl_hash:
    description: "The Leeway hash of the dev/preview/previewctl:docker package to be used when downloading previewclt"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
