name: "Preview environment garbage collection"
on:
    workflow_dispatch:
    schedule:
        - cron: "0 */4 * * *"
jobs:
    create-runner:
        uses: ./.github/workflows/create_runner.yml
        secrets: inherit

    stale:
        name: "Find stale preview environments"
        runs-on: ${{ needs.create-runner.outputs.label }}
        needs: [ create-runner ]
        container:
            image: eu.gcr.io/gitpod-core-dev/dev/dev-environment:aledbf-new-dev-image-gha.13182
        outputs:
            names: ${{ steps.set-matrix.outputs.names }}
            count: ${{ steps.set-matrix.outputs.count }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Compute matrix
              id: set-matrix
              shell: bash
              env:
                  PREVIEW_ENV_DEV_SA_KEY: ${{ secrets.GCP_CREDENTIALS }}
              run: |
                set -euo pipefail

                export GOOGLE_APPLICATION_CREDENTIALS=${{ steps.auth.outputs.credentials_file_path }}

                gcloud auth activate-service-account --key-file ${{ steps.auth.outputs.credentials_file_path }}

                leeway run dev/preview/previewctl:install

                previewctl get-credentials --gcp-service-account ${{ steps.auth.outputs.credentials_file_path }}
                previewctl list stale | jq --null-input --raw-input --compact-output '[inputs | select(length>0)]' > /tmp/stale-json
                echo "names=$(cat /tmp/stale-json)" >> $GITHUB_OUTPUT
                echo "count=$(jq '. | length' /tmp/stale-json)" >> $GITHUB_OUTPUT

    delete:
        name: "Delete preview environment"
        needs: [ stale, create-runner ]
        runs-on: ${{ needs.create-runner.outputs.label }}
        if: ${{ needs.stale.outputs.count > 0 }}
        strategy:
            fail-fast: false
            matrix:
                name: ${{ fromJSON(needs.stale.outputs.names) }}
        steps:
            - uses: actions/checkout@v3
            - name: Delete preview environment ${{ matrix.name }}
              uses: ./.github/actions/delete-preview
              with:
                  name: ${{ matrix.name }}
                  sa_key: ${{ secrets.GCP_CREDENTIALS }}

    delete-runner:
        if: always()
        needs:
        - create-runner
        - stale
        - delete
        uses: ./.github/workflows/remove_runner.yml
        secrets: inherit
        with:
            runner-label: ${{ needs.create-runner.outputs.label }}
